# These are supported funding model platforms

github: T3rrabyte
patreon: t3lakuna
open_collective: # Replace with a single Open Collective username
ko_fi: Lakuna
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: Lakuna
issuehunt: t3rrabyte
otechie: Lakuna
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
